/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{html,js}',
    '../app/src/**/*.rs',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#b6a0ff',
        'primary-dim': '#7e51ff',
        'primary-fixed': '#a98fff',
        'primary-fixed-dim': '#9c7eff',
        'on-primary-fixed': '#000000',
        'on-primary-fixed-variant': '#32008a',
        'on-primary-container': '#280072',
        secondary: '#00d2fd',
        'secondary-dim': '#00c3eb',
        'secondary-fixed': '#79dfff',
        'secondary-fixed-dim': '#1cd5ff',
        'on-secondary-fixed': '#003a47',
        'on-secondary-fixed-variant': '#00586c',
        'secondary-container': '#00677e',
        'on-secondary-container': '#eefaff',
        tertiary: '#ff96bb',
        'tertiary-dim': '#ee77a3',
        'tertiary-fixed': '#ff8db6',
        'tertiary-fixed-dim': '#f57ca9',
        'tertiary-container': '#fb81ae',
        'on-tertiary': '#690939',
        'on-tertiary-fixed': '#37001a',
        'on-tertiary-fixed-variant': '#70103e',
        'on-tertiary-container': '#59002e',
        background: '#0a0e14',
        surface: '#0a0e14',
        'surface-dim': '#0a0e14',
        'surface-bright': '#262c36',
        'surface-variant': '#20262f',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#0f141a',
        'surface-container': '#151a21',
        'surface-container-high': '#1b2028',
        'surface-container-highest': '#20262f',
        'surface-tint': '#b6a0ff',
        'on-surface': '#f1f3fc',
        'on-surface-variant': '#a8abb3',
        'on-background': '#f1f3fc',
        'on-primary': '#340090',
        'on-secondary': '#004352',
        'inverse-surface': '#f8f9ff',
        'inverse-on-surface': '#51555c',
        'inverse-primary': '#6834eb',
        outline: '#72757d',
        'outline-variant': '#44484f',
        error: '#ff6e84',
        'error-dim': '#d73357',
        'error-container': '#a70138',
        'on-error': '#490013',
        'on-error-container': '#ffb2b9',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        lg: '0.5rem',
        xl: '0.75rem',
      },
    },
  },
  plugins: [],
};
