/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{html,js}',
    '../app/src/**/*.rs',
  ],
  theme: {
    extend: {
      colors: {
        primary: 'oklch(var(--noir-primary) / <alpha-value>)',
        'primary-dim': 'oklch(var(--noir-primary-dim) / <alpha-value>)',
        'primary-fixed': '#a98fff',
        'primary-fixed-dim': '#9c7eff',
        'on-primary-fixed': '#000000',
        'on-primary-fixed-variant': '#32008a',
        'on-primary-container': '#280072',
        secondary: 'oklch(var(--noir-secondary) / <alpha-value>)',
        'secondary-dim': 'oklch(var(--noir-secondary-dim) / <alpha-value>)',
        'secondary-fixed': '#79dfff',
        'secondary-fixed-dim': '#1cd5ff',
        'on-secondary-fixed': '#003a47',
        'on-secondary-fixed-variant': '#00586c',
        'secondary-container': '#00677e',
        'on-secondary-container': '#eefaff',
        tertiary: 'oklch(var(--noir-tertiary) / <alpha-value>)',
        'tertiary-dim': 'oklch(var(--noir-tertiary-dim) / <alpha-value>)',
        'tertiary-fixed': '#ff8db6',
        'tertiary-fixed-dim': '#f57ca9',
        'tertiary-container': '#fb81ae',
        'on-tertiary': '#690939',
        'on-tertiary-fixed': '#37001a',
        'on-tertiary-fixed-variant': '#70103e',
        'on-tertiary-container': '#59002e',
        background: 'oklch(var(--noir-background) / <alpha-value>)',
        surface: 'oklch(var(--noir-background) / <alpha-value>)',
        'surface-dim': 'oklch(var(--noir-background) / <alpha-value>)',
        'surface-bright': 'oklch(var(--noir-surface-bright) / <alpha-value>)',
        'surface-variant': 'oklch(var(--noir-surface-highest) / <alpha-value>)',
        'surface-container-lowest': 'oklch(var(--noir-surface-lowest) / <alpha-value>)',
        'surface-container-low': 'oklch(var(--noir-surface-low) / <alpha-value>)',
        'surface-container': 'oklch(var(--noir-surface) / <alpha-value>)',
        'surface-container-high': 'oklch(var(--noir-surface-high) / <alpha-value>)',
        'surface-container-highest': 'oklch(var(--noir-surface-highest) / <alpha-value>)',
        'surface-tint': 'oklch(var(--noir-primary) / <alpha-value>)',
        'on-surface': 'oklch(var(--noir-foreground) / <alpha-value>)',
        'on-surface-variant': 'oklch(var(--noir-muted-foreground) / <alpha-value>)',
        'on-background': 'oklch(var(--noir-foreground) / <alpha-value>)',
        'on-primary': 'oklch(var(--noir-on-primary) / <alpha-value>)',
        'on-secondary': 'oklch(var(--noir-on-secondary) / <alpha-value>)',
        'inverse-surface': '#f8f9ff',
        'inverse-on-surface': '#51555c',
        'inverse-primary': '#6834eb',
        outline: 'oklch(var(--noir-outline) / <alpha-value>)',
        'outline-variant': '#44484f',
        error: 'oklch(var(--noir-destructive) / <alpha-value>)',
        'error-dim': '#d73357',
        'error-container': '#a70138',
        'on-error': '#490013',
        'on-error-container': '#ffb2b9',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['Space Grotesk', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        label: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        lg: 'var(--noir-radius)',
        xl: 'calc(var(--noir-radius) + 0.25rem)',
        '2xl': 'var(--noir-radius-card)',
        '3xl': 'calc(var(--noir-radius-card) + 0.5rem)',
      },
      boxShadow: {
        ambient: 'var(--noir-shadow-ambient)',
        'glow-primary': 'var(--noir-shadow-glow-primary)',
      },
      backgroundImage: {
        'noir-primary': 'var(--noir-gradient-primary)',
        'noir-hero': 'var(--noir-gradient-hero)',
      },
    },
  },
  plugins: [],
};
