/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{html,js}',
    '../app/src/**/*.rs',
  ],
  theme: {
    extend: {
      colors: {
        primary: 'oklch(var(--noir-primary) / <alpha-value>)',
        'primary-dim': 'oklch(var(--noir-primary-dim) / <alpha-value>)',
        'primary-fixed': 'oklch(0.78 0.16 60)',
        'primary-fixed-dim': 'oklch(0.7 0.15 60)',
        'on-primary-fixed': '#0b0b0d',
        'on-primary-fixed-variant': '#0b0b0d',
        'on-primary-container': '#ffffff',
        secondary: 'oklch(var(--noir-secondary) / <alpha-value>)',
        'secondary-dim': 'oklch(var(--noir-secondary-dim) / <alpha-value>)',
        'secondary-fixed': 'oklch(0.8 0.14 195)',
        'secondary-fixed-dim': 'oklch(0.6 0.13 195)',
        'on-secondary-fixed': '#0b0b0d',
        'on-secondary-fixed-variant': '#0b0b0d',
        'secondary-container': 'oklch(0.3 0.08 195)',
        'on-secondary-container': '#ffffff',
        tertiary: 'oklch(var(--noir-tertiary) / <alpha-value>)',
        'tertiary-dim': 'oklch(var(--noir-tertiary-dim) / <alpha-value>)',
        'tertiary-fixed': 'oklch(0.68 0.15 300)',
        'tertiary-fixed-dim': 'oklch(0.6 0.13 300)',
        'tertiary-container': 'oklch(0.3 0.08 300)',
        'on-tertiary': '#0b0b0d',
        'on-tertiary-fixed': '#0b0b0d',
        'on-tertiary-fixed-variant': '#0b0b0d',
        'on-tertiary-container': '#ffffff',
        background: 'rgb(var(--noir-background) / <alpha-value>)',
        surface: 'rgb(var(--noir-background) / <alpha-value>)',
        'surface-dim': 'rgb(var(--noir-background) / <alpha-value>)',
        'surface-bright': 'rgb(var(--noir-surface-bright) / <alpha-value>)',
        'surface-variant': 'rgb(var(--noir-surface-highest) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--noir-surface-lowest) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--noir-surface-low) / <alpha-value>)',
        'surface-container': 'rgb(var(--noir-surface) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--noir-surface-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--noir-surface-highest) / <alpha-value>)',
        'surface-tint': 'oklch(var(--noir-primary) / <alpha-value>)',
        'on-surface': 'rgb(var(--noir-foreground) / <alpha-value>)',
        'on-surface-variant': 'oklch(var(--noir-muted-foreground) / <alpha-value>)',
        'on-background': 'rgb(var(--noir-foreground) / <alpha-value>)',
        'on-primary': 'rgb(var(--noir-on-primary) / <alpha-value>)',
        'on-secondary': 'rgb(var(--noir-on-secondary) / <alpha-value>)',
        success: 'oklch(var(--noir-success) / <alpha-value>)',
        warning: 'oklch(var(--noir-warning) / <alpha-value>)',
        disabled: 'oklch(var(--noir-disabled-foreground) / <alpha-value>)',
        'inverse-surface': '#f8f9ff',
        'inverse-on-surface': '#51555c',
        'inverse-primary': '#6834eb',
        outline: 'oklch(var(--noir-outline) / <alpha-value>)',
        'outline-variant': '#44484f',
        error: 'oklch(var(--noir-destructive) / <alpha-value>)',
        'error-dim': '#d73357',
        'error-container': '#a70138',
        'on-error': '#490013',
        'on-error-container': '#ffb2b9',
      },
      fontFamily: {
        headline: ['ui-monospace', 'SFMono-Regular', 'Consolas', 'monospace'],
        display: ['ui-monospace', 'SFMono-Regular', 'Consolas', 'monospace'],
        body: ['ui-monospace', 'SFMono-Regular', 'Consolas', 'monospace'],
        label: ['ui-monospace', 'SFMono-Regular', 'Consolas', 'monospace'],
      },
      borderRadius: {
        lg: 'var(--noir-radius)',
        xl: 'var(--arc-radius-md)',
        '2xl': 'var(--noir-radius-card)',
        '3xl': 'var(--arc-radius-dialog)',
      },
      boxShadow: {
        ambient: 'var(--noir-shadow-ambient)',
        'glow-primary': 'var(--noir-shadow-glow-primary)',
        menu: '0 8px 24px rgb(0 0 0 / 50%)',
      },
      backgroundImage: {
        'noir-primary': 'var(--noir-gradient-primary)',
        'noir-hero': 'var(--noir-gradient-hero)',
      },
    },
  },
  plugins: [],
};
